### ISSUE TITLE
Can I update README with what Linda:// does?

### ISSUE THREAD

**Issue by DogeDevYT** [linda-project/linda#26]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by DogeDevYT** [comment]
basically what exactly does linda do/simplify and can I update readme so that further contributors dont' have to ask you?

**Comment by d1snin** [comment]
> basically what exactly does linda do/simplify and can I update readme so that further contributors dont' have to ask you?

Linda is currently in the early beta, there is no documentation yet and I'm basically the only one understanding the specification. Documentation describing every aspect will be ready soon, I need to fix some major issues before it. When the documentation is ready, I'll write the simple Getting started guide.
