### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by d1snin** [linda-project/linda#4]
All dependencies are already ready for writing Swagger documentation for the API as well as wiki

**Comment by kibibites** [comment]
~10k LoC and still no documentation

when documentation

**Comment by d1snin** [comment]
Stay in tune. Documentation is pointless without the base implementation. Although, it's next in the project backlog.

**Comment by d1snin** [comment]
![IMG_20220416_035710_935.jpg](https://user-images.githubusercontent.com/68169685/163655663-439397ce-60e6-4378-b673-4a69d270c992.jpg)

**Comment by d1snin** [comment]
@i-spin Documentation is still WIP, but you can review the *getting started* guide I made. Suggest your improvements right here.
**https://d1snin.gitbook.io/linda/guides/getting-started-with-linda**
